### ISSUE TITLE
demo doesn't work; phrasefinder.search doesn't work

### ISSUE THREAD

**Issue by zsiegel92** [mtrenkmann/phrasefinder-client-python#3]
Hey there,

When I run demo.py I get an error. I removed the `try`/`except`, and got this traceback:

    Traceback (most recent call last):
      File "demo.py", line 35, in <module>
        main()
      File "demo.py", line 17, in main
        result = phrasefinder.search(query, options)
      File "/Users/Zach/datamuse_test/phrasefinder/src/phrasefinder.py", line 113, in search
        result.quota = int(context.info()["X-Quota"])
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rfc822.py", line 393, in __getitem__
        return self.dict[name.lower()]
    KeyError: 'x-quota'

Since I don't need `result.quota`, I commented out line 113 in phrasefinder.py:

    result.quota = int(context.info()["X-Quota"])

Other users may still want `result.quota`, so I would temporarily set that to 0 until I figured that problem out. I can look into it and submit a pull request unless you (the author) sees a quick fix.

Best wishes.

**Comment by mtrenkmann** [comment]
Hi, thanks for reporting,

I recently removed any rate limiting, so there is no `X-Quota` header field anymore. I pull request that fixes this problem would be very nice. I think removing line 90 and 113 in `phrasefinder.py` would do it. After your PR I will regenerate the docs.

Cheers!

**Comment by mtrenkmann** [comment]
Fixed since v0.2.0 release. Thanks for reporting!

**Comment by zsiegel92** [comment]
Thanks!
